name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'opensuse', tag: 'latest', continue-on-error: 'true'}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1
        with:
          repository: junghans/${{ matrix.config.dockerfile }}
          registry: ghcr.io
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          push: false
